### ISSUE TITLE
Assignment Questions

### ISSUE THREAD

**Issue by akontovasilakos** [mariosp/cat-image-app#1]
Hello Marios,

First of all, let me thank you for taking the time to complete and submit this assignment. Your efforts are much appreciated.

We have a few follow up questions, and it would be great if you could take some time to answer:
- Do you generally use any tools for code formatting? Seems there is a mix of formats throughout your project.
- Could you please let us know, if and how would you improve the `src/services/api.ts` file?
- Could you please elaborate a bit on your decision to use Redux? Do you have any experience with other state management libraries?

Again, thanks a lot for your time,
Alexandros

**Comment by mariosp** [comment]
Hi Alexandre,

1)
Yes, for code formatting I use Prettier. I also use it with a pre-commit hook to make it impossible to commit unformatted code.

For this project, I did not use a formatting tool.

2)
α) The API key is used in every request, so it should be a constant variable. We could also have the API key in an env variable.
b) We can use the Header and SearchParams objects instead of passing the params directly. Also, all endpoints use the same headers, so we could create and use only one instance of the object in every endpoint.
c) Return type should be specified, for example, Promise<Cat[]>
d) getRandomCats and getCatsByBreedId use the same endpoint with different search parameters. We can remove the duplicate code by sharing the code in a function and passing the search params of the endpoint as function parameters.
e) File name can be more specific, for example, catApi.ts 

You can find the changes for the above here: (branch f1 [f1 branch](https://github.com/mariosp/cat-image-app/compare/main...f1))

3)
Redux is the state management tool I use mostly in React applications. It has a lot of boilerplate code but it can be a good choice as the application grows as it provides a lot of tools and capabilities. Also, the unidirectional data flow and the pure functions for reducers make it easier to understand and debug.

In the project, I use it to keep the state of the fetched cats and breeds, so they will be rendered without fetching them again, and also to keep the state of the favorite cats.

Other state management libs I have used:
React: recoil, mobX
Angular: NgRx, NGXS

Thank you

**Comment by akontovasilakos** [comment]
Good morning Marie,

Thanks a lot for your responses and for the new branch as well!
